# Gradle properties
group = com.varlanv.koper
version = 0.0.1-SNAPSHOT
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.configuration-cache=true
org.gradle.configuration-cache.parallel=true
#org.gradle.isolated-projects=true
#org.gradle.isolated-projects.diagnostics=true
org.gradle.configuration-cache-problems=warn
org.gradle.warning.mode=summary
org.gradle.jvmargs=-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

# INTERNAL
internalConventionMs=2g
internalConventionMx=4g

# VERSIONS
foojayToolchainPluginVersion=1.0.0
